Algoritmo "calculaMedia"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/04/2022
Var
name: caractere
n1: real
n2: real

Inicio

escreva("Insira seu nome: ")
leia(name)
escreva("Insira n1: ")
leia(n1)
escreva("Insira n2: ")
leia(n2)
escreva("A media do aluno ", name, " foi ", (n1 + n2)/2)

Fimalgoritmo