Algoritmo "Soma dois números"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/04/2022
Var
exit: caractere
n1: inteiro
n2: inteiro

Inicio

exit <- "n"
enquanto exit <> "s" faca
escreval("insira n1: ")
leia(n1)
escreval("insira n2: ")
leia(n2)
escreval("n1 + n2 = ", n1 + n2)
escreval("Deseja sair? s/n")
leia(exit)
fimenquanto

Fimalgoritmo